INSERT INTO prompt (category, category_cn, content) VALUES
('LivingRoom', '客厅', 'A cinematic product shot on a modern wooden coffee table in a luxurious living room, soft natural lighting through windows, shallow depth of field, 8k quality, photorealistic, product photography style'),
('LivingRoom', '客厅', 'Elegant product display on a minimalist white table in a contemporary living room, indirect warm lighting, gentle camera motion rotating around the item, high-end commercial photography, crystal clear details'),
('Bedroom', '床上', 'Elegant display on plush neutral bedding, dreamy bedroom atmosphere, gentle floating camera motion, soft natural lighting, premium hotel room style, cinematic mood, shallow depth of field'),
('Bedroom', '床上', 'Artistic display on premium cotton sheets, morning golden hour lighting, graceful dolly movement, contemporary bedroom setting, lifestyle photography, subtle fabric movement, professional color grading'),
('Kitchen', '厨房', 'Professional product display on modern kitchen countertop, bright natural lighting from window, marble surface, clean minimal kitchen background, smooth sliding camera movement, commercial grade quality'),
('Kitchen', '厨房', 'Elegant showcase on granite kitchen counter, warm ambient lighting, professional kitchen setting, subtle depth of field, slow panning shot, spotless surfaces, culinary atmosphere'),
('Yacht', '游艇', 'Close-up product shot on a wooden table on luxury yacht deck, smooth circular camera movement around the product, natural sunlight, ocean background, ultra HD, product perfectly centered on elegant wooden table, gentle ocean waves visible in background, cinematic lighting, 35mm lens'),
('Yacht', '游艇', 'Side tracking shot moving past product on modern white table, luxury yacht deck setting, ocean view background, smooth steady cam movement, soft natural lighting, gentle ocean movement, cinematic color grading, premium quality'),
('Hardware', '五金', 'Industrial pegboard wall with organized hardware tools, dramatic side lighting, metal and wood textures, professional workshop setting, high contrast, commercial product photography, 8k resolution'),
('Hardware', '五金', 'Hardware store display style, tools professionally arranged on wooden shelf, emphasis on product details and practical features, clear commercial lighting, focus stacking for maximum detail, retail catalog quality');
